- name: Dart
  logo: dart
  url: https://dart.dev/
  color: 52C0F2
  logoColor: FFFFFF
  projects:
    - url: https://github.com/nailuj29gaming/flutter_countdown
    - wip: true
    
- name: Flutter
  logo: flutter
  url: https://flutter.dev/
  color: 52C0F2
  logoColor: FFFFFF
  projects:
    - url: https://github.com/nailuj29gaming/flutter_countdown
    - wip: true


- name: Android
  logo: android
  url: https://developer.android.com
  color: 3DDC84
  logoColor: FFFFFF
  projects:
    - https://github.com/nailuj29gaming/countdown-android
