name: Profile Stack

on:
  push:
    branches:
      - master

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gliech/profile_stack@master
